version: '3.7'
services:
  php:
    build: ./docker/php
    links:
      - mariadb
    volumes:
      - .:/application

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    links:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/application

  mariadb:
    image: mariadb:10.1.40
    volumes:
      - mariadb-volume:/var/lib/mariadb
    environment:
      MYSQL_DATABASE: ddd-symfony-skeleton
      MYSQL_ROOT_PASSWORD: password

volumes:
  mariadb-volume:
