<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRa1dSM0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRa1dSM0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRa1dSM0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRa1dSM0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRa1dSM0\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ra1dSM0',
    'container.build_id' => '1194a5a3',
    'container.build_time' => 1574857860,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRa1dSM0');
