<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK3gq0oM\Infrastructure_Symfony_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK3gq0oM/Infrastructure_Symfony_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK3gq0oM.legacy');

    return;
}

if (!\class_exists(Infrastructure_Symfony_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK3gq0oM\Infrastructure_Symfony_KernelDevDebugContainer::class, Infrastructure_Symfony_KernelDevDebugContainer::class, false);
}

return new \ContainerK3gq0oM\Infrastructure_Symfony_KernelDevDebugContainer([
    'container.build_hash' => 'K3gq0oM',
    'container.build_id' => 'c9756e6c',
    'container.build_time' => 1574865324,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK3gq0oM');
